server:
  port: ${PORT:8084}

spring:
  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.feastly.user: DEBUG
