CREATE TABLE IF NOT EXISTS app_users (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  mobile VARCHAR(30) NOT NULL,
  password VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL
);
