FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY backend .
RUN mvn -pl restaurant-service -am package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/restaurant-service/target/restaurant-service-0.1.0.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
