server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

services:
  restaurant-url: http://localhost:8081
  order-url: http://localhost:8082
  user-url: http://localhost:8084

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.feastly.gateway: DEBUG
